services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=iir4
      - MYSQL_USER=root
      - MYSQL_DB=todos
    command: sh-c "yarn install && yarn run dev"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=iir4
    volumes:
      - MYSQL_DATABASE=todos:/var/lib/mysql/todos
      - todo-mysql-data:/var/lib/mysql
  todo-mysql-data:

